---
language: go
go:
  - 1.13.x
install: true
notifications:
  irc: "chat.freenode.net#openshift-dev"
matrix:
  allow_failures:
    - go: master
  fast_finish: true
services:
  - docker
env:
  global:
    - S2I_GIT_VERSION=""
    - S2I_GIT_MAJOR=""
    - S2I_GIT_MINOR=""
install:
  - make install-travis
script:
  # running project linting, static tests
  - make verify
  # running unit tests
  - make test TESTFLAGS="-p=4 -v" TESTS="''"
  # running integration tests with Docker container manager
  - S2I_CONTAINER_MANAGER="docker" make test-docker
  # running integration tests with buildah container manager, using sudo to be able to mount local
  # container images on file-system
  - S2I_CONTAINER_MANAGER="buildah" sudo -E env "PATH=$PATH" make test-docker
