---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
  - name: iscsipd-ro
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: iscsipd-ro
  - name: iscsipd-rw
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: iscsipd-rw
  volumes:
  - name: iscsipd-ro
    iscsi:
      targetPortal: 10.0.2.15:3260
      iqn: iqn.2001-04.com.example:storage.kube.sys1.xyz
      lun: 0
      fsType: ext4
      readOnly: true
  - name: iscsipd-rw
    iscsi:
      targetPortal: 10.0.2.15:3260
      iqn: iqn.2001-04.com.example:storage.kube.sys1.xyz
      lun: 1
      fsType: ext4
      readOnly: false
