#!/bin/bash -x

touch /sti-fake-builder/prepare-invoked
mkdir -p /usr/build/

if [ -e /usr/artifacts/save-artifacts-invoked ]; then
  touch /usr/build/save-artifacts-invoked
fi

cp -ad /usr/src /usr/build/
