apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/source-to-image?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" &&
      target_branch == "master"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: source-to-image
    appstudio.openshift.io/component: source-to-image
    pipelines.appstudio.openshift.io/type: build
  name: source-to-image-on-pull-request
  namespace: ocp-tools-s2i-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocp-tools-s2i-tenant/source-to-image:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Dockerfile
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: build-platforms
    value:
      - linux/x86_64
      - linux/arm64
      - linux/ppc64le
#      - linux/s390x
  - name: prefetch-input
    value: '{"packages": [{"type": "gomod"}]}'
  pipelineRef:
    resolver: bundles
    params:
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-multi-platform-oci-ta@sha256:575d73f29fa40c387eb5853966d6135e09020417d3f444a1cd9c1fd426788bb6
      - name: name
        value: docker-build-multi-platform-oci-ta
      - name: kind
        value: pipeline
